<?php

$funcionarios = [
    [
        'id' => 'maria-souza',
        'nome' => 'Maria da Silva e Souza',
        'cargo' => 'Diretora Pedagógica',
        'departamento' => 'Diretoria',
        'foto' => 'https://placehold.co/300x300/B7E4F6/105F7E?text=Maria+Souza',
        'descricao' => 'Líder visionária com mais de 20 anos de experiência em gestão educacional.',
        'formacao' => 'Mestrado em Gestão Escolar e Pedagogia',
        'redes_sociais' => [
            'linkedin' => 'https://www.linkedin.com/in/mariasilva',
        ],
    ],
    [
        'id' => 'carlos-pereira',
        'nome' => 'Carlos Alberto Pereira',
        'cargo' => 'Coordenador do Ensino Médio',
        'departamento' => 'Coordenação',
        'foto' => 'https://placehold.co/300x300/B7E4F6/105F7E?text=Carlos+Pereira',
        'descricao' => 'Dedicação total ao desenvolvimento acadêmico e pessoal dos alunos.',
        'formacao' => 'Pós-graduação em Metodologias Ativas e Licenciatura em Matemática',
        'redes_sociais' => [
            'linkedin' => 'https://www.linkedin.com/in/carlospereira',
        ],
    ],
    [
        'id' => 'ana-goncalves',
        'nome' => 'Ana Paula Gonçalves',
        'cargo' => 'Professora de Português e Redação',
        'departamento' => 'Docente - Linguagens',
        'foto' => 'https://placehold.co/300x300/B7E4F6/105F7E?text=Ana+Goncalves',
        'descricao' => 'Apaixonada por literatura e pela arte de escrever.',
        'formacao' => 'Licenciatura em Letras - Português/Literatura',
        'redes_sociais' => [],
    ],
    [
        'id' => 'roberto-santos',
        'nome' => 'Roberto Oliveira Santos',
        'cargo' => 'Professor de Matemática',
        'departamento' => 'Docente - Exatas',
        'foto' => 'https://placehold.co/300x300/B7E4F6/105F7E?text=Roberto+Santos',
        'descricao' => 'Torna os números divertidos e acessíveis a todos os alunos.',
        'formacao' => 'Licenciatura em Matemática e Mestre em Educação Matemática',
        'redes_sociais' => [],
    ],
    [
        'id' => 'julia-costa',
        'nome' => 'Júlia Mendes da Costa',
        'cargo' => 'Professora de Biologia',
        'departamento' => 'Docente - Ciências da Natureza',
        'foto' => 'https://placehold.co/300x300/B7E4F6/105F7E?text=Julia+Costa',
        'descricao' => 'Explorando o mundo da vida em laboratório e em campo.',
        'formacao' => 'Licenciatura em Ciências Biológicas',
        'redes_sociais' => [
            'instagram' => 'https://www.instagram.com/juliabiologia',
        ],
    ],
    [
        'id' => 'fernando-lima',
        'nome' => 'Fernando Antunes Lima',
        'cargo' => 'Professor de História',
        'departamento' => 'Docente - Humanas',
        'foto' => 'https://placehold.co/300x300/B7E4F6/105F7E?text=Fernando+Lima',
        'descricao' => 'Viajando no tempo para entender o presente e construir o futuro.',
        'formacao' => 'Licenciatura em História e Especialização em Geopolítica',
        'redes_sociais' => [],
    ],
    [
        'id' => 'patricia-almeida',
        'nome' => 'Patrícia Vieira Almeida',
        'cargo' => 'Secretária Escolar',
        'departamento' => 'Administrativo',
        'foto' => 'https://placehold.co/300x300/B7E4F6/105F7E?text=Patricia+Almeida',
        'descricao' => 'Organização e eficiência para o bom funcionamento da secretaria.',
        'formacao' => 'Técnico em Secretariado e Graduação em Gestão Pública',
        'redes_sociais' => [],
    ],
    [
        'id' => 'guilherme-ferreira',
        'nome' => 'Guilherme Castro Ferreira',
        'cargo' => 'Orientador Educacional',
        'departamento' => 'Coordenação',
        'foto' => 'https://placehold.co/300x300/B7E4F6/105F7E?text=Guilherme+Ferreira',
        'descricao' => 'Apoia alunos e famílias no desenvolvimento de suas jornadas educacionais.',
        'formacao' => 'Graduação em Psicologia e Pós-graduação em Orientação Educacional',
        'redes_sociais' => [
            'linkedin' => 'https://www.linkedin.com/in/guilhermeorientador',
        ],
    ],
    [
        'id' => 'adriana-nunes',
        'nome' => 'Adriana Batista Nunes',
        'cargo' => 'Professora de Química',
        'departamento' => 'Docente - Ciências da Natureza',
        'foto' => 'https://placehold.co/300x300/B7E4F6/105F7E?text=Adriana+Nunes',
        'descricao' => 'Desvendando os segredos da matéria e suas transformações.',
        'formacao' => 'Licenciatura em Química',
        'redes_sociais' => [],
    ],
    [
        'id' => 'marcelo-silva',
        'nome' => 'Marcelo Gomes e Silva',
        'cargo' => 'Professor de Educação Física',
        'departamento' => 'Docente - Linguagens', // Educação Física é parte das linguagens no ENEM
        'foto' => 'https://placehold.co/300x300/B7E4F6/105F7E?text=Marcelo+Silva',
        'descricao' => 'Promovendo a saúde e o bem-estar através do esporte e movimento.',
        'formacao' => 'Licenciatura em Educação Física',
        'redes_sociais' => [],
    ],
    [
        'id' => 'suzana-paz',
        'nome' => 'Suzana Rodrigues da Paz',
        'cargo' => 'Bibliotecária',
        'departamento' => 'Administrativo',
        'foto' => 'https://placehold.co/300x300/B7E4F6/105F7E?text=Suzana+Paz',
        'descricao' => 'Guardiã do conhecimento e incentivadora da leitura.',
        'formacao' => 'Graduação em Biblioteconomia',
        'redes_sociais' => [],
    ],
    [
        'id' => 'ricardo-monteiro',
        'nome' => 'Ricardo Alves Monteiro',
        'cargo' => 'Professor de Geografia',
        'departamento' => 'Docente - Humanas',
        'foto' => 'https://placehold.co/300x300/B7E4F6/105F7E?text=Ricardo+Monteiro',
        'descricao' => 'Desvendando os espaços geográficos e suas interconexões.',
        'formacao' => 'Licenciatura em Geografia',
        'redes_sociais' => [],
    ],
     // --- Novos Funcionários de Apoio ---
     [
        'id' => 'joana-costa',
        'nome' => 'Joana Lima Costa',
        'cargo' => 'Cozinheira',
        'departamento' => 'Apoio Operacional',
        'foto' => 'https://placehold.co/300x300/B7E4F6/105F7E?text=Joana+Cozinheira',
        'descricao' => 'Responsável por preparar refeições nutritivas e saborosas para todos.',
        'formacao' => 'Curso de Culinária e Higiene Alimentar',
        'redes_sociais' => [],
    ],
    [
        'id' => 'pedro-silva',
        'nome' => 'Pedro Henrique Silva',
        'cargo' => 'Auxiliar de Limpeza',
        'departamento' => 'Apoio Operacional',
        'foto' => 'https://placehold.co/300x300/B7E4F6/105F7E?text=Pedro+Faxineiro',
        'descricao' => 'Garante que todos os ambientes da escola estejam sempre limpos e organizados.',
        'formacao' => 'Treinamento em Higiene e Limpeza Profissional',
        'redes_sociais' => [],
    ],
    [
        'id' => 'claudia-medeiros',
        'nome' => 'Cláudia Mendes Medeiros',
        'cargo' => 'Cozinheira Auxiliar',
        'departamento' => 'Apoio Operacional',
        'foto' => 'https://placehold.co/300x300/B7E4F6/105F7E?text=Claudia+Cozinheira',
        'descricao' => 'Ajuda a equipe da cozinha a manter a qualidade e o sabor das refeições.',
        'formacao' => 'Experiência em Cozinha Coletiva',
        'redes_sociais' => [],
    ],
    [
        'id' => 'marcos-rocha',
        'nome' => 'Marcos Vinicius Rocha',
        'cargo' => 'Guarda Escolar',
        'departamento' => 'Segurança',
        'foto' => 'https://placehold.co/300x300/B7E4F6/105F7E?text=Marcos+Guarda',
        'descricao' => 'Zela pela segurança e tranquilidade de alunos e funcionários.',
        'formacao' => 'Curso de Segurança Patrimonial e Primeiros Socorros',
        'redes_sociais' => [],
    ],
    [
        'id' => 'sofia-martins',
        'nome' => 'Sofia Antunes Martins',
        'cargo' => 'Auxiliar de Limpeza',
        'departamento' => 'Apoio Operacional',
        'foto' => 'https://placehold.co/300x300/B7E4F6/105F7E?text=Sofia+Faxineira',
        'descricao' => 'Contribui para um ambiente escolar sempre acolhedor e limpo.',
        'formacao' => 'Experiência em Organização e Limpeza',
        'redes_sociais' => [],
    ],
    [
        'id' => 'antonio-gomes',
        'nome' => 'Antônio Dias Gomes',
        'cargo' => 'Guarda Escolar',
        'departamento' => 'Segurança',
        'foto' => 'https://placehold.co/300x300/B7E4F6/105F7E?text=Antonio+Guarda',
        'descricao' => 'Responsável pelo controle de acesso e monitoramento das instalações.',
        'formacao' => 'Treinamento em Segurança e Prevenção',
        'redes_sociais' => [],
    ],

];