<?php

$itinerarios = [
    [
        'id' => 'itinerario-biologia',
        'titulo' => 'Biologia em Foco: Vida e Sustentabilidade',
        'descricao' => 'Explore os mistérios da vida e o impacto ambiental das ações humanas.',
        'descricao_completa' => 'O itinerário de Biologia proporciona uma imersão no estudo dos seres vivos, ecossistemas, genética, microbiologia e saúde pública. Envolve atividades práticas em laboratório, saídas de campo e projetos de preservação ambiental, desenvolvendo a consciência ecológica e o interesse pelas ciências da vida.',
        'imagem_fundo' => 'imagensItinerarios\Biologia.png',
        'icone' => 'fas fa-leaf',
        'categorias' => ['Biológicas', 'Ciências Naturais', 'Saúde'],
        'projetos_imagens' => [
            ['url' => 'imagensItinerarios\Biologia.png', 'legenda' => 'Visita dos alunos a um laboratório'],
            ['url' => 'imagens\Itinerarios\Biologia1.png', 'legenda' => 'Aluno realizando tipagem sanguínea'],
            ['url' => 'imagens\Itinerarios\Biologia2.png', 'legenda' => 'Aluna participando de atividade prática de tipagem sanguínea'],
            ['url' => 'imagens\Itinerarios\Biologia3.png', 'legenda' => 'Demonstração do processo de tipagem sanguínea'],
        ],
    ],
    [
        'id' => 'itinerario-danca-movimento',
        'titulo' => 'Dança e Movimento: Expressão Corporal e Cultura',
        'descricao' => 'Desenvolva sua expressão artística e consciência corporal por meio da dança.',
        'descricao_completa' => 'Este itinerário trabalha a linguagem corporal, consciência do corpo, ritmo, coreografia e cultura por meio da dança. Os alunos vivenciam diferentes estilos e contextos culturais, além de desenvolverem autoconfiança, trabalho em grupo e expressão artística.',
        'imagem_fundo' => 'imagensItinerarios\Dança.png',
        'icone' => 'fas fa-music',
        'categorias' => ['Artes', 'Educação Física', 'Expressão Corporal'],
        'projetos_imagens' => [
            ['url' => 'imagensItinerarios\Dança.png', 'legenda' => 'Ensaio para apresentações coreográficas em eventos escolares'],
            ['url' => 'imagens\Itinerarios\danca1.png', 'legenda' => 'Estudos sobre danças regionais brasileiras'],
        ],
    ],
    [
        'id' => 'itinerario-empreendedorismo',
        'titulo' => 'Empreendedorismo Criativo: Inovação e Negócios',
        'descricao' => 'Aprenda a transformar ideias em oportunidades de negócio.',
        'descricao_completa' => 'Neste itinerário, os alunos desenvolvem habilidades para planejar, gerenciar e executar ideias empreendedoras. São abordados temas como plano de negócios, marketing, finanças pessoais, inovação, criatividade e resolução de problemas. Ideal para quem quer abrir seu próprio negócio ou atuar de forma autônoma no mercado.',
        'imagem_fundo' => 'imagensItinerarios\Empreendedorismo.png',
        'icone' => 'fas fa-lightbulb',
        'categorias' => ['Negócios', 'Economia', 'Criatividade'],
        'projetos_imagens' => [
            ['url' => 'imagensItinerarios\Empreendedorismo.png', 'legenda' => 'Feira de Gastronomia: exposição de pratos variados pelos alunos'],
            ['url' => 'imagens\Itinerarios\Empreendedorismo1.png', 'legenda' => 'Stand de geleias'],
            ['url' => 'imagens\Itinerarios\Empreendedorismo2.png', 'legenda' => 'Stand de salgados'],
            ['url' => 'imagens\Itinerarios\Empreendedorismo3.png', 'legenda' => 'Stand de bolos'],
        ],
    ],
    [
        'id' => 'itinerario-ganhando-o-mundo',
        'titulo' => 'Ganhando o Mundo: Conexões Globais e Intercâmbio',
        'descricao' => 'Prepare-se para o intercâmbio cultural com foco em cidadania global.',
        'descricao_completa' => 'Itinerário voltado ao desenvolvimento de competências linguísticas, culturais e sociais para alunos interessados em intercâmbio pelo programa Ganhando o Mundo. Envolve estudo de línguas, culturas estrangeiras, atualidades internacionais, além de estimular autonomia, empatia e cidadania global.',
        'imagem_fundo' => 'imagensItinerarios\Ganhando-o-Mundo.png',
        'icone' => 'fas fa-globe-americas',
        'categorias' => ['Internacional', 'Linguagens', 'Cidadania Global'],
        'projetos_imagens' => [
            ['url' => 'imagensItinerarios\Ganhando-o-Mundo.png', 'legenda' => 'Aluna vencedora do programa Ganhando o Mundo com destino ao Canadá'],
            ['url' => 'imagens\Itinerarios\Ganhando-o-mundo1.png', 'legenda' => 'Apresentação da aluna brasileira na escola canadense'],
            ['url' => 'imagens\Itinerarios\Ganhando-o-mundo2.png', 'legenda' => 'Alunos selecionados para o intercâmbio'],
        ],
    ],
    [
        'id' => 'itinerario-historia-tempo',
        'titulo' => 'História e o Tempo: Caminhos da Humanidade',
        'descricao' => 'Viaje no tempo analisando eventos e transformações sociais.',
        'descricao_completa' => 'Este itinerário investiga os processos históricos que moldaram a sociedade contemporânea. Trabalha com análise crítica de documentos, filmes, museus e debates sobre cidadania, democracia, guerras, cultura e direitos humanos. Desenvolve habilidades investigativas e pensamento histórico.',
        'imagem_fundo' => 'imagensItinerarios\Historia e o tempo.png',
        'icone' => 'fas fa-landmark',
        'categorias' => ['Humanas', 'História', 'Cultura'],
        'projetos_imagens' => [
            ['url' => 'imagensItinerarios\Historia e o tempo.png', 'legenda' => 'Apresentação de um relógio solar criado pelos alunos'],
            ['url' => 'imagens\Itinerarios\historiaetempo1.png', 'legenda' => 'Alunos demonstrando o funcionamento de uma ampulheta artesanal'],
            ['url' => 'imagens\Itinerarios\historiaetempo3.png', 'legenda' => 'Exposição de diferentes formas de medir o tempo na antiguidade'],
            ['url' => 'imagens\Itinerarios\historiaetempo2.png', 'legenda' => 'Detalhe de uma ampulheta feita pelos estudantes'],
              
        ],
    ],
    [
        'id' => 'itinerario-maos-a-horta',
        'titulo' => 'Mãos à Horta: Cultivando Saberes',
        'descricao' => 'Aprenda na prática como cultivar alimentos e valorize a sustentabilidade.',
        'descricao_completa' => 'Este itinerário envolve os alunos em atividades práticas de cultivo, manutenção e colheita de alimentos na horta escolar. Eles aprendem sobre agricultura sustentável, alimentação saudável, compostagem, respeito ao meio ambiente e trabalho coletivo, desenvolvendo senso de responsabilidade e conexão com a natureza.',
        'imagem_fundo' => 'imagensItinerarios\maos a horta.png',
        'icone' => 'fas fa-seedling',
        'categorias' => ['Ambiental', 'Biológicas', 'Habilidades Essenciais'],
        'projetos_imagens' => [
            ['url' => 'imagensItinerarios\maos a horta.png', 'legenda' => 'Alunos verificando o crescimento de um pé de alface'],
            ['url' => 'imagens\Itinerarios\Maos-a-horta1.png', 'legenda' => 'Pesagem de alface colhida na horta pelos alunos'],
            ['url' => 'imagens\Itinerarios\Maos-a-horta2.png', 'legenda' => 'Professora explicando técnicas de cultivo na horta escolar'],],
    ],
    [
        'id' => 'itinerario-praticas-experimentais',
        'titulo' => 'Práticas Experimentais: Ciência em Ação',
        'descricao' => 'Descubra o mundo por meio de experimentos científicos e investigação.',
        'descricao_completa' => 'Voltado para alunos interessados em ciências naturais, esse itinerário promove a investigação científica com experiências práticas em laboratório. Estimula o raciocínio lógico, a curiosidade e o método científico, além de desenvolver habilidades para resolver problemas do cotidiano com base em evidências.',
        'imagem_fundo' => 'imagensItinerarios\praticas-experimentais.png',
        'icone' => 'fas fa-vials',
        'categorias' => ['Exatas', 'Biológicas', 'Investigação Científica'],
        'projetos_imagens' => [
            ['url' => 'imagensItinerarios\praticas-experimentais.png', 'legenda' => 'Experimento com Becker'],
            ['url' => 'imagens\Itinerarios\praticas-experimentais2.png', 'legenda' => 'Professora explicando observações sobre a amostra de frango'],
            ['url' => 'imagens\Itinerarios\praticas-experimentais1.png', 'legenda' => 'Amostra de coxinha de frango sendo observada ao microscópio'],
            ['url' => 'imagens\Itinerarios\praticas-experimentais3.png', 'legenda' => 'Imagem ampliada da coxinha de frango vista pelo microscópio'],
        ],
    ],
    [
        'id' => 'itinerario-redacao-leitura',
        'titulo' => 'Redação e Leitura: Comunicação e Argumentação',
        'descricao' => 'Aprimore sua escrita e leitura crítica com foco em vestibulares.',
        'descricao_completa' => 'Itinerário voltado ao desenvolvimento da competência leitora e escritora. Trabalha produção de textos, interpretação, análise crítica, gramática aplicada e construção de argumentos. Ideal para quem busca melhorar a redação para o ENEM, concursos e vida acadêmica.',
        'imagem_fundo' => 'imagensItinerarios\Redacao-E-Leitura.png',
        'icone' => 'fas fa-book-open',
        'categorias' => ['Linguagens', 'Comunicação', 'Preparatório ENEM'],
        'projetos_imagens' => [
            ['url' => 'imagensItinerarios\Redacao-E-Leitura.png', 'legenda' => 'Aluno fazendo resumo textual durante a aula'],
            ['url' => 'imagens\Itinerarios\Redacao-Leitura1.png', 'legenda' => 'Leitura do livro "O Pequeno Príncipe" em sala de aula'],
            ['url' => 'imagens\Itinerarios\Redacao-Leitura2.png', 'legenda' => 'Professora explicando tema de redação para os alunos'],
        ],
    ],
    [
        'id' => 'itinerario-tecnico-agronegocio',
        'titulo' => 'Técnico em Agronegócio: Gestão e Produção Sustentável',
        'descricao' => 'Desenvolva competências técnicas para atuar no setor do agronegócio.',
        'descricao_completa' => 'Esse itinerário técnico prepara o aluno para atuar nas áreas de produção agrícola, comercialização, gestão rural e sustentabilidade. Envolve conteúdos práticos e teóricos sobre cadeia produtiva, mecanização, legislação, economia e tecnologias aplicadas ao campo.',
        'imagem_fundo' => 'imagensItinerarios\TecnicoAgroNegocio.png',
        'icone' => 'fas fa-tractor',
        'categorias' => ['Técnico', 'Rural', 'Gestão'],
        'projetos_imagens' => [
           ['url' => 'imagensItinerarios\TecnicoAgroNegocio.png', 'legenda' => 'Alunos em frente a um pulverizador agrícola'],
            ['url' => 'imagens\Itinerarios\TecnicoAgroNegocio1.png', 'legenda' => 'Alunos escutando explicações de um profissional do agronegócio'],
            ['url' => 'imagens\Itinerarios\TecnicoAgroNegocio2.png', 'legenda' => 'Momento de aprendizado com especialista da área agrícola'],
        ],
    ],[
        'id' => 'itinerario-xadrez',
        'titulo' => 'Xadrez: Estratégia e Raciocínio Lógico',
        'descricao' => 'Desenvolva o pensamento estratégico e a concentração com o xadrez.',
        'descricao_completa' => 'O itinerário de Xadrez propõe o ensino dos fundamentos do jogo, estimulando o raciocínio lógico, a tomada de decisão, a concentração e o respeito às regras. Além do aprendizado técnico, promove torneios internos e desafios que desenvolvem habilidades cognitivas e socioemocionais.',
        'imagem_fundo' => 'imagensItinerarios\xadrez.webp',
        'icone' => 'fas fa-chess',
        'categorias' => ['Lógica', 'Raciocínio', 'Socioemocional'],
        'projetos_imagens' => [
            ['url' => 'imagensItinerarios\xadrez.webp', 'legenda' => 'Início do Campeonato Interescolar de Xadrez'],
            ['url' => 'imagens\Itinerarios\xadrez1.png', 'legenda' => 'Alunos competindo no torneio de xadrez'],
            ['url' => 'imagens\Itinerarios\xadrez2.png', 'legenda' => 'Campeões do Campeonato Interescolar de Xadrez'],
        ],
    ],
    
];